// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc1lGeOhQsU40piSw5J7pmXsmcIYRyEbY',
    appId: '1:210284553469:web:1c1ff1685c03273af6ca94',
    messagingSenderId: '210284553469',
    projectId: 'szop-df434',
    authDomain: 'szop-df434.firebaseapp.com',
    storageBucket: 'szop-df434.appspot.com',
    measurementId: 'G-5BJBBV07B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApr6cF76chM3iQy5t41b0Krt3cUbWvCCU',
    appId: '1:210284553469:android:032a3b38ff563a74f6ca94',
    messagingSenderId: '210284553469',
    projectId: 'szop-df434',
    storageBucket: 'szop-df434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcCiJcowjEg8xmDnm5EDZp4f1wue4L_zk',
    appId: '1:210284553469:ios:c6c2fa9a4a852e0af6ca94',
    messagingSenderId: '210284553469',
    projectId: 'szop-df434',
    storageBucket: 'szop-df434.appspot.com',
    iosBundleId: 'com.example.zop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcCiJcowjEg8xmDnm5EDZp4f1wue4L_zk',
    appId: '1:210284553469:ios:f4f14654ff2af5a3f6ca94',
    messagingSenderId: '210284553469',
    projectId: 'szop-df434',
    storageBucket: 'szop-df434.appspot.com',
    iosBundleId: 'com.example.zop.RunnerTests',
  );
}
